version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 513410254886.dkr.ecr.ap-south-1.amazonaws.com
      - IMAGE_URI=513410254886.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest $IMAGE_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI:latest
      - echo Build completed
